apiVersion: v1
kind: Service
metadata:
  name: dashboard-api-db
  labels:
    app: dashboard-api
    role: persistence
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  selector:
    app: dashboard-api
    role: persistence