apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-api
  labels:
    control-plane: dashboard-api
    role: backend
spec:
  selector:
    matchLabels:
      control-plane: dashboard-api
      role: backend
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: dashboard-api
        role: backend
    spec:
      containers:
        - image: controller:latest
          name: dashboard-api
          imagePullPolicy: Always
          envFrom:
          - configMapRef:
              name: postgresql-env
          env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-pw
                key: postgres-password
      terminationGracePeriodSeconds: 10
